### ISSUE TITLE
Swagger 사용 시 jackson library 버전 충돌이 있는 듯 합니다

### ISSUE THREAD

**Issue by mottoslo** [HangHae-Sprint/SPrint-Server#20]
기존 sprint조회 시 createdAt을 LocalDateTime으로 반환하여 jackson library가 파싱하여 클라이언트에게 반환했었는데, swagger 적용 후에 이상하게 파싱되는 문제가 있습니다. 적용된 swagger의 버전이 jacksonlibrary의 예전 버전을 사용하는 문제인 것 같습니다.

**Comment by InyongHwang** [comment]
swagger를 springfox-swagger-ui에서 sprintdoc-openapi-ui로 변경했습니다.

**Comment by mottoslo** [comment]
고생하셨습니다 !

**Comment by mottoslo** [comment]
이유는 모르겠지만 다시 같은 문제가 발생했습니다 허허

**Comment by mottoslo** [comment]
comment의 createdAt, modifiedAt은 원하는 대로 잘 나오는거 보니까 JSON 파싱 문제는 아닌 것 같기도 합ㄴ디ㅏ

**Comment by mottoslo** [comment]
Comment 부분도 array로 쪼개져서 파싱되어 나옵니다...! 이유를 못찾겠어서 일단  API 명세 수정하고 이대로 가야할 것 같스빈다
