### ISSUE TITLE
좋아요 POST요청 했을때 CORSerror 뜨는 이슈

### ISSUE THREAD

**Issue by stella0905** [HangHae-Sprint/SPrint-Server#32]
좋아요 POST요청 보내면 CORSerror만 에러가 뜨는 이슈가 있습니다. 

다른 API요청은 잘 되는 상태입니다. 
확인 부탁드립니다.

**Comment by mottoslo** [comment]
특정 요청에 대해서만 CORS 허용이 안되는 이유를 아직 모르겠습니다. 오늘 특강 끝나고 보겠습니다 ..!

**Comment by InyongHwang** [comment]
죄송합니다.. 어제 저희끼리 스프린트 좋아요의 `url`을 `api/like/{sprintId}`에서.... 댓글 좋아요 기능을 추가할 경우를 대비해서 `api/like/sprint/{sprintId}`로 하기로 하고 그렇게 코드를 작성했는데..... api명세서도 수정 안해놓고... 공유도 안드리고.....
죄송합니다..
