### ISSUE TITLE
기능 구현하면서 안된 문제 

### ISSUE THREAD

**Issue by stella0905** [HangHae-Sprint/SPrint-Server#39]
토큰 없을때 all List 안받아와집니다.
전체리스트 받아올때 게시물 작성자의 nickname 을 가져오는게 아니고 로그인한 유저의 nickname을 가져와집니다.
댓글 작성 CORS 에러납니다.
상세조회할때 commentList에 commentId를 불러오지 못합니다. 정확하게 이해도 되지 않습니다.  일단 명세서에 안적혀 있음 추가도 안되서 볼 수 도 없어서 뭐가 맞는건지도 모르겠습니다.
신청서 보낼때 알수없는 이상한 에러가 뜹니다. 내가 쓴 게시물에는 신청할수없다는건 잘 들어옵니다..

"could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"

**Comment by mottoslo** [comment]
1. 토큰없을때 allList 안받아지는 문제 : 임시유저를 삭제해서 그렇습니다. 해결완료
2. 전체리스트 게시물 작성자 버그 : 수정했습니다
3. 댓글작성 CORS 문제 : API 명세 요청 URL 문제 (수정완료)
4. commentList에 담겨오는 Id가 commentId입니다. 혼선을 방지하기 위해 commentId 필드에 담아서 드리는걸로 수정했습니다
5. SQL 에러 : 참가 신청 요청에 link -> githubLink 해주시면 될 것 같습니다. API 명세가 바뀌었네요 ..
